Load config once (twice at most) instead of often.
Less messy, double brackets everything, comments!

Added a useful on_error example.

Renamed the on_error.sh, it is not a sh script, so .sh is silly

Add a clean method to remove logfiles.

diff --git a/bin/mongroup b/bin/mongroup
--- a/bin/mongroup
+++ b/bin/mongroup
@@ -41,7 +41,13 @@ EOF
 alive() {
   kill -0 $1 2> /dev/null
 }
-
+#
+# Clean up after ourselves
+#
+clean() {
+  rm $pid_dir/*
+  rm $log_dir/*
+}
 #
 # Abort with <msg ...>
 #
@@ -52,31 +58,7 @@ abort() {
   echo
   exit 1
 }
-# working: mon -p ./pids/web.pid -m ./pids/web.mon.pid -l ./logs/web.log --on-error "./on_error.sh web" "node server.js 8001"
-# not working: mon -p ./pids/web.pid -m ./pids/web.mon.pid -l ./logs/web.log --on-error ./on_error.sh web node server.js 8001
-# double quotations needed!
 
-
-
-# Read configuration file.
-#
-
-read_config() {
-  if [ ! -f $config_file ]; then
-    abort $config_file doesn\'t exist
-  fi
-  . $config_file
-  
-  if [ ! -d $pid_dir ]; then
-    abort $pid_dir directory doesn\'t exist
-  fi
-
-  if [ ! -d $log_dir ]; then
-    abort $log_dir directory doesn\'t exist
-  fi
-}
-
-#
 # Set config <file>
 #
 
@@ -95,16 +77,16 @@ start_proc() {
     -m "$pid_dir/$1.mon.pid"
     -l "$log_dir/$1.log")
 
-  if [ -n "$attempts" -a "$attempts" != "" -a -f "$attempts" ]
-  then
+  # if $attempts is not empty and is a number.  
+  if [[ -n $attempts && $attempts != *[!0-9]* ]] ; then
     mon_opts+=(--attempts "$attempts")
   fi
-  if [ -n "$on_error" -a "$on_error" != "" -a -f "$on_error" ]
-  then
+  # if $on_error is not empty and is a regular file.
+  if [[ -n $on_error && -f $on_error ]] ; then
     mon_opts+=(--on-error ""$on_error" "$name"")
   fi
-  if [ -n "$on_restart" -a "$on_restart" != "" -a -f "$on_restart" ]
-  then
+  # if $on_error is not empty and is a regular file.
+  if [[ -n $on_restart && -f $on_restart ]] ; then
     mon_opts+=(--on-restart ""$on_restart" "$name"")
   fi
   shift; mon_opts+=("${args[*]}")
@@ -116,22 +98,28 @@ start_proc() {
 #
 
 start() {
-  read_config
   local app=$1
+  # loop all processes loaded from config file.
   for name in "${processes[@]}"; do
     ref=$name[@]; args=( "${!ref}" );
     local pidfile=$PIDS/$name.pid
-    if [ -z "$app" -o "$app" == "$name" ]; then
-      if [ -f $pidfile ]; then
-        local pid=$(cat $pidfile)
+    # $app is empty or $name is the process we want ($app)
+    if [[ -z $app ||  $app == $name ]]; then
+      # if the pid file is a regular file
+      if [[ -f $pidfile ]]; then
+        local pid=$(cat $pidfile) # read the pid
+        # check if process is alive.
         alive $pid
-        if [ $? -eq 0 ]; then
+        # exitcode of alive is 0 means the process is not running.
+        if [[ $? -eq 0 ]]; then
           printf "  \e[36m%10s\e[m : %s\n" "running" $name
         else
+        # process is not running, start it up.
           start_proc $name "${args[@]}"
         fi
       else
-        start_proc "$name" "${args[@]}"
+        # pid file did not exist (the process can't be running), start it up.
+        start_proc $name "${args[@]}"
       fi
     fi
   done
@@ -142,13 +130,12 @@ start() {
 #
 
 status() {
-  read_config
   echo
   for name in "${processes[@]}"; do
     ref=$name[@]; args=( "${!ref}" );
     local pidfile=$pid_dir/$name.pid
     printf "  %10s : " $name
-    if [ -f $pidfile ]; then
+    if [[ -f $pidfile ]]; then
       echo `mon --pidfile $pidfile --status`
     else
       printf "\e[31mdead\e[m\n"
@@ -162,11 +149,10 @@ status() {
 #
 
 stop() {
-  read_config
   local app=$1
   for name in "${processes[@]}"; do
     ref=$name[@]; args=( "${!ref}" );
-    if [ -z "$app" -o "$app" == "$name" ]; then
+    if [[ -z $app || $app == $name ]]; then
       printf "  \e[36m%10s\e[m : %s\n" "stop" $name
       kill -s SIGQUIT $(cat $pid_dir/$name.mon.pid) 2> /dev/null
     fi
@@ -187,7 +173,6 @@ restart() {
 #
 
 tail_log() {
-  read_config
   local app=$2
   local arg=$1
   local log_files=
@@ -195,15 +180,15 @@ tail_log() {
 
   for name in "${processes[@]}"; do
     ref=$name[@]; args=( "${!ref}" );
-    if [ -z "$app" -o "$app" == "$name" ]; then
+    if [[ -z $app || $app == $name ]]; then
       log_files[i]="$log_dir/$name.log"
     fi
   done
 
-  if [[ "$arg" == "less" ]]; then
+  if [[ $arg == "less" ]]; then
     less -R ${log_files[@]}
   else
-    if [ "$arg" == "logf" -o "$arg" == "tail" ]; then
+    if [[ $arg == "logf" || $arg == "tail" ]]; then
       follow="-f"
     fi
     tail -n 30 $follow ${log_files[@]}
@@ -226,9 +211,30 @@ update() {
     && echo "updated $version -> `mongroup --version`"
 }
 
+load_config() {
+  # check if the config file exists.
+  if [ ! -f $config_file ]; then
+    abort $config_file doesn\'t exist
+  fi
+  # source the config file.
+  . $config_file
+
+  # check if the pid directory is a valid directory.
+  if [ ! -d $pid_dir ]; then
+    abort $pid_dir directory doesn\'t exist
+  fi
+
+  # check if the log directory is a valid directory.
+  if [ ! -d $log_dir ]; then
+    abort $log_dir directory doesn\'t exist
+  fi
+}
+# load the config first, reload it later if someone sets --cofig
+load_config
+
 # default to status
 
-if [ $# -eq 0 ]; then
+if [[ $# -eq 0 ]]; then
   status
   exit
 fi
@@ -246,16 +252,21 @@ while test $# -ne 0; do
       exit
       ;;
     -V|--version)
-      echo $VERSION
+      echo $version
       exit
       ;;
     -c|--config)
       set_config $1
+      load_config
       shift
+      ;;
+    clean)
+      clean
+      exit
       ;;
     start)
       echo
-      start $1
+      handle_start $@
       echo
       exit
       ;;
